# This secret contains the values used to connect to a broker
{{- if hasKey .Values.kafka "brokers" }}
apiVersion: v1
data:
  brokers: {{ .Values.kafka.brokers | b64enc | quote }}
  {{- if hasKey .Values.kafka "namespace" }}
  namespace: {{ .Values.kafka.namespace | b64enc | quote}}
  {{- end }}
  password: {{ .Values.kafka.password | b64enc | quote}}
  username: {{ .Values.kafka.username | b64enc | quote}}
kind: Secret
metadata:
  name: {{ .Values.kafka.secretName }}
  namespace: {{ .Values.global.namespace.runtime }}
  labels:
    knativekafka.kyma-project.io/kafka-secret: "true"
type: Opaque
{{- end }}
