apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: kafkachannels.knativekafka.kyma-project.io
spec:
  group: knativekafka.kyma-project.io
  names:
    kind: KafkaChannel
    plural: kafkachannels
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            numPartitions:
              format: int64
              minimum: 1
              type: integer
            replicationFactor:
              format: int64
              minimum: 1
              type: integer
            retentionMillis:
              format: int64
              minimum: 1
              type: integer
            subscribable:
              description: Channel conforms to Duck type Subscribable.
              properties:
                subscribers:
                  description: This is the list of subscriptions for this subscribable.
                    +patchMergeKey=uid +patchStrategy=merge
                  items:
                    properties:
                      generation:
                        description: Generation of the origin of the subscriber with
                          uid:UID.
                        format: int64
                        type: integer
                      ref:
                        description: 'Deprecated: use UID.'
                        type: object
                      replyURI:
                        type: string
                      subscriberURI:
                        type: string
                      uid:
                        description: UID is used to understand the origin of the subscriber.
                        type: string
                    type: object
                  type: array
              type: object
            tenantId:
              description: Kafka Topics names are limited to 255 characters and the
                specified regex.  This implementation will, however, append the KafkaChannel's
                Namespace and Name to the TenantId.  We don't know how long those
                might be, so use with caution.
              maxLength: 200
              minLength: 1
              pattern: '[a-zA-Z0-9_\-\.\\]+'
              type: string
          type: object
        status:
          properties:
            address:
              properties:
                Addressable:
                  properties:
                    url:
                      type: object
                  type: object
                hostname:
                  type: string
              type: object
            conditions:
              description: Conditions the latest available observations of a resource's
                current state. +patchMergeKey=type +patchStrategy=merge
              items:
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime is the last time the condition
                      transitioned from one status to another. We use VolatileTime
                      in place of metav1.Time to exclude this from creating equality.Semantic
                      differences (all other things held constant).
                    type: object
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  severity:
                    description: Severity with which to treat failures of this type
                      of condition. When this is not specified, it defaults to Error.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                      +required
                    type: string
                  type:
                    description: Type of condition. +required
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            observedGeneration:
              description: ObservedGeneration is the 'Generation' of the Service that
                was last processed by the controller.
              format: int64
              type: integer
            subscribablestatus:
              properties:
                subscribers:
                  description: This is the list of subscription's statuses for this
                    channel. +patchMergeKey=uid +patchStrategy=merge
                  items:
                    properties:
                      message:
                        description: A human readable message indicating details of
                          Ready status.
                        type: string
                      observedGeneration:
                        description: Generation of the origin of the subscriber with
                          uid:UID.
                        format: int64
                        type: integer
                      ready:
                        description: Status of the subscriber.
                        type: string
                      uid:
                        description: UID is used to understand the origin of the subscriber.
                        type: string
                    type: object
                  type: array
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
